language: python
dist: bionic
python:
  - "3.6"
addons:
  apt:
    packages:
    - gir1.2-gtk-3.0
    - libgirepository1.0-dev
    - libapt-pkg-dev
    - fakeroot
install:
  - pip install -r requirements.txt
<<<<<<< HEAD
script:
  - sudo mv /etc/dpkg/dpkg.cfg.d/pkg-config-hook-config ..
  - ./pyruntests pep8 small
=======

env:
  - TESTFOLDER="pep8 small"
  - TESTFOLDER="medium"
script: PATH="/usr/bin:$PATH" ./runtests $TESTFOLDER
>>>>>>> add requirements
